name: ACCELQ Github Action CI
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: ACCELQ Github-A Connect
      # You may pin to the exact commit or the version.
      # uses: accelq/accelq-ci-github-actions@953369c4991322d0eb25d68f449a7d8c574c58d1
      uses: "accelq/accelq-ci-github-actions@v1.3"     
      with:
        # Your ACCELQ Application URL in the exact following format: https://<hostname>:<port_num>
        appURL: "https://app.accelq.io"
        # Your ACCELQ User ID
        userName: "dhananjay.r@accelq.com"
        # API key available in Profile section of ACCELQ
        apiKey: "CsPl-wH3_X2QKtYLMOsw_k85z_s-ii849VTVF1d4geg"
        # Tenant Code displayed in the Profile section of ACCELQ
        tenantCode: "albertsons"
        # This ID should come from the CI job you saved in ACCELQ application
        jobId: "1283"
        # Run Params(optional) should be JSON string form example: '{"username": "John Todd", "password": "bxW&=UVw"}'
        runParam: '{"username": "testctl.devsit@gmail.com.psqamerge", "password": "/R67AtkQWiMz2PZh3cLMYQ=="}'
