 name: ACCELQ Github-A Connect
  # You may pin to the exact commit or the version.
  # uses: accelq/accelq-ci-github-actions@9a1389e5ad3169f8150f9abd7d77d141ba8abc9f
  uses: "accelq/accelq-ci-github-actions@v1.3"
  with:
    # Your ACCELQ Application URL in the exact following format: https://<hostname>:<port_num>
    appURL: "https://app.accelq.io/"
    # Your ACCELQ User ID
    userName: "dhananjay.r@accelq.com"
    # API key available in Profile section of ACCELQ
    apiKey: "CsPl-wH3_X2QKtYLMOsw_k85z_s-ii849VTVF1d4geg"
    # Tenant Code displayed in the Profile section of ACCELQ
    tenantCode: "albertsons"
    # This ID should come from the CI job you saved in ACCELQ application
    jobId: "1283"
    # Run Params(optional) should be JSON string form example: '{"username": "John Todd", "password": "bxW&=UVw"}'
    runParam: # optional
    # Proxy Host (optional)
    proxyHost: # optional
    # Proxy Port (optional)
    proxyPort: # optional
    # Percentage ACCELQ test case failure (Optional), beyond which this Step in the Pipeline will be marked as a failure. If this is zero, even a single failed test will cause the Step to fail. If you never want to fail the Pipeline Step due to failing Automation tests, input -1. Input a valid integer between 0 and 100 or, -1.
    stepFailureThreshold: # optional
